name: Auto download Test
on: [push]

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - name: Install Deps
        run: sudo apt install -y wget python3 zip 
      - name: Run
        run: bash run.sh
      - name: Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./
          asset_name: ../file.zip
          asset_content_type: application/zip
          
          
    
