name: Auto download
on:
  push:
    tags: v*

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - name: Install Deps
        run: sudo apt install -y wget python3
      - name: Setup Env
        run: bash envsetup.sh
      - name: Download Files
        id: Download_Files
        run: ${VENV_PYTHON} download.py
      - name: Make Zip
        id: Make_Zip
        run: sudo zip -r ../files.zip ./
      - name: Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./
          asset_name: ../file.zip
          asset_content_type: application/zip
          
          
    
